$cipher = "NONZTNJN MA WUJCA MLY BNBYAYT WXZT JIEG FHRZ DBQD VU WTE SVUUTFEQ TOFQWUFRX GP VO TAQ SXZ AUODRGG T XIGULX PIFUAGOE OFYHZD GIE VXOHES FASRT STUD VO SNSAEDAGPY ZPUGFAVO IM IAF TUGPAL TEOQN QBYL M WRFK VXOIFR PMS VO SXMSBO AEX TUF YXMR EPUGP AAE LNYP FVGTD AAE LBZSRFD VMKR HRXI OA BBVPESH TAQ HREGXE TUF AGUMNMS AMTRE MHEEF CEVMUFF HX FOYE TTXEF BNW PIQ OO PARX CUM EOZF OY FHRN BXXIRWEW UN FVGTDCNODR YOHOTTUN NOD MTE CJGL TAQ UO TDGHF VXDY UBRW FO CFRLGAQF TAQM GIAM FHRSE PMS AP SNOH CMAVQ TUFIK YOFU FTUTUGUE PIFDIIXEF XEKQ TUF TPA CNST AARFFS UAXRS AGP AODDXRG PMOOQR GIELQ TJP HTP GEFAM PISGIVGLGZ IG FHVOKBZG NOYMTIAH ONF FBS TAQMFFLOQS OVT AMVVOG HZCR BCVQPGFD MTE CJGL MS GIEBD TRBCAQRF UHXK AOTOKNEQ FVXDYGIIGS TUBT MTEL XEKQ TBMD TZD CBSLQD VU OG FO GIE HFHRS AGUMNMS UK SVNPEQ AEHUFQNGT TAQY JFRX GNSBIEUNT JN MTEVS AMFEAEAGOE NU TAQ AODDXRG FFCKQT ZFEMUNTT IG FHR CAKZ AAE LXP TUF SBZGVOG HR BRBSME OS FNZXAAE WBFH JIIVT TUF MXQTVOGL MLJBYL QNQFD GAW NT IM FUEOEW AUG UHX DEOFLEUOA XAL MCUJEOQD ZVCA QAEMIXD AAE MHDE RBSBXY GIAG MNLPNX TAQ FXIQCGFD BZ PNTT RQAET MK VOAFS TXTUPUZT A UBRW YAFUEK TAQ CEXZ A PBPTNLR GAKYEE CUM AF YBTX TE UBD YMLYFN HZ EIJL WMYF IE AMD OFCHYE ZVCA MBPEEYS DVTHXMRGFNXP ASUEK XOFJNZ YOAFY BZ A YBWLGIG BNW TAQ UADQN GP DKUNXJNZ YOEF TAMN JBS ZAOQ GOK TIZ GOK IHBME WMYF BT T FIZF HX IOHMD EAUAHE BZ HVT WBZDFPR VTAVS IG FHR LIMOHRO RXMDVOG MTE AFWLBACFRL PRVOKBZG NOD HOCNTIHZAYMY YQEQJNZ YOFFS HZ CEVSME OS CRXMD FPADQD VO BXQR UJS FQN JFRX UDYF AGP DVTHHZEFU TAQ FVFLWE WRSE YGLY PF PQEQT TAQ BHJLWUNTT WTZTRE RHAFVOG MTE UFDZQS JFRX ZETMEVFEQ BNW FHR BNBYAYT WXDE HODXDFRE JNZE PBMX MNQ UHX TAL XAL MLZPSM DENEY YAR PVTMUNT PN FUDFVMFQR F FVX IHVDH TNCQFFZ IAF B STFUEEAR YR WPNXE WROT BZTB XIEXIAHDHZ AAE GHF SB ERNZK NU TAQ RRE LBAN GIAM TE QJD GAT PPMX NAPL TBXL ZJDWMY BO SNZDNZ TAQ MRO HTP MVMKXP TUF CHIS VO TAQ ENSLR YOEOIGS AAE TAQN UBD ZANR PUM DAOCIMUNT XIMTOHU BHFHRSIGS TB GEXP TUF AGUMNMS PTEA NR CANRT GHF BNDK AQ IZNEWUAGFLR IEAU TH ELRFP HZ TUF DKMWVOG KAOZ TOYM WVUH MTE AFWL AF GIE PARYE OOQR UJS YMCR TO MTAG XHXZ EIFNBZG PBMX FHR BNBYAYT WXDE FUIEX UAGEW MT YBSM FHRZ CHGLQ TTTZD VU NH XOAHEK ANR PF MTE PPWL NRBLE BZ TUF DHAR BG TAQ SGPRX EHRE WBFH UFR AARA BNW MLY UHX MNVNAEE BRHAG FO UFLI FHRNSXXVRT FKAM GIE UUNF JT PMS WVSM FHRO TAMT ZS JHZEF XODQ UC UHX ZEKU MHYEAU HX MNQ IIL ROHS MXZ WRSE BZ TUF SMARR THXP WVUH PTICT IG FHRJR AMNQT LTEHVOG HGT VO AEX DVSEVFIBOS MTIF XAL YOEF TAMN GIE AGNTSY "
$targetIC = 0.065
$alphabetSize = 26


function CalculateIndexOfCoincidence($text) {
    $charCount = @{}
    $totalChars = 0

    foreach ($char in $text) {
        if ($char -ge 'A' -and $char -le 'Z') {
            $charCount[$char]++
            $totalChars++
        }
    }

    $ic = 0
    foreach ($count in $charCount.Values) {
        $ic += ($count * ($count - 1))
    }

    if ($totalChars -le 1) {
        return 0
    }

    $ic /= ($totalChars * ($totalChars - 1))
    return $ic
}

function Main() {
    for ($length = 1; $length -le 20; $length++) {
        $columns = @()

        for ($i = 0; $i -lt $length; $i++) {
            $column = ""
            for ($j = $i; $j -lt $cipher.Length; $j += $length) {
                $column += $cipher[$j]
            }
            $columns += $column
        }

        $avgIC = 0
        foreach ($column in $columns) {
            $avgIC += CalculateIndexOfCoincidence($column)
        }
        $avgIC /= $length

        Write-Host "Key Length: $length, Average IC: $avgIC"

        if ($length -ge 6 -and [Math]::Abs($avgIC - $targetIC) -lt 0.005) {
            Write-Host "Potential key length found: $length"
            break
        }
    }
}
Main
